import Head from "next/head";
import Image from "next/image";
import { useRouter } from 'next/router';
import { Inter } from "next/font/google";
import styles from "@core/styles/Home.module.css";
import { Game, GameData } from "@core/components/game";
import { generate } from "random-words";

const inter = Inter({ subsets: ["latin"] });

const Home: React.FC<{ game: GameData, onRefresh: () => void }> = ({ game }) => {
  const router = useRouter();
  const onRefresh = () => {
    router.replace(router.asPath);
  }

  return (
    <>
      <Head>
        <title>Wordle game</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1 user-scalable=no" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Game game={game} onRefresh={onRefresh} />
      </main>
    </>
  );
}

export default Home;

export async function getServerSideProps({ query }) {
  // This could be an HTTP request to get the game session preferences
  const x = parseInt(query.x) || 5;
  const y = parseInt(query.y) || 6;
  const grid = [x, y];
  const [wordLength] = grid;
  const word = generate({
    minLength: wordLength,
    maxLength: wordLength,
  }) as string;

  const game = {
    grid,
    rounds: y,
    word: word.toUpperCase(),
  };

  return { props: { game } };
}
